"""creating table weather

Revision ID: 879f1cddbbda
Revises: a27fbbde4096
Create Date: 2023-10-26 00:21:08.666747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879f1cddbbda'
down_revision: Union[str, None] = 'a27fbbde4096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_region', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('temp', sa.Integer(), nullable=False),
    sa.Column('feel_like', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('wind_speed', sa.Integer(), nullable=False),
    sa.Column('wind_dir', sa.String(), nullable=False),
    sa.Column('pressure_mm', sa.Integer(), nullable=False),
    sa.Column('pressure_pa', sa.Integer(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('sunrise', sa.String(), nullable=False),
    sa.Column('sunset', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
